function paz_bashrc_sourceFile() {
	BASHDIR=$1

	if [ ! -d "${BASHDIR}" ]; then
		return;
	fi


	SCRIPTS=$(find $BASHDIR -type f -perm -u=x | sort)
	for script in $SCRIPTS
	do
		if [ -x $script ]; then
			. $script
		fi
	done
}

paz_bashrc_sourceFile "$HOME/.scripts/env.d/global/bash.d/"
paz_bashrc_sourceFile "$HOME/.scripts/env.d/current/bash.d/"
